module.exports = {
  ADD_MAP: 'ADD_MAP',
  ADD_INFO: 'ADD_INFO',
  REMOVE_CARD: 'REMOVE_CARD',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  SAVE_SIGNUP: 'SAVE_SIGNUP',
  ADD_PIN: 'ADD_PIN'
};
